apiVersion: v1
kind: Secret
metadata:
    name: docker-io-helm-oci
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
    selfLink: /api/v1/namespaces/argocd/secrets/docker-io-helm-oci
data:
    enableOCI: dHJ1ZQ==
    name: Yml0bmFtaWNoYXJ0cw==
    type: aGVsbQ==
    url: cmVnaXN0cnktMS5kb2NrZXIuaW8vYml0bmFtaWNoYXJ0cw==
type: Opaque
