apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: ingress-nginx
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.11.1
        helm:
            parameters:
                - name: controller.service.type
                  value: NodePort
        chart: ingress-nginx
    destination:
        server: https://kubernetes.default.svc
        namespace: ingress-nginx
    syncPolicy:
        syncOptions:
            - CreateNamespace=true
